//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.MnMn.MnMn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.MnMn.MnMn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;update&lt;/title&gt;
        ///	&lt;style&gt;
        ///		* {
        ///			font-family: Consolas, &quot;Meiryo UI&quot;, monospace;
        ///			font-size: 14pt;
        ///		}
        ///
        ///		h1 {
        ///			text-align: center;
        ///		}
        ///
        ///		#content {
        ///			display: flex;
        ///			justify-content: center;
        ///			align-items: center;
        ///		}
        ///
        ///		#timestamp {
        ///			text-align: center;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h1&gt;${UPDATE-TITLE}&lt;/h1&gt;
        ///	&lt;div id=&quot;content&quot;&gt;
        ///		${UPDATE-CONTENT}
        ///	&lt;/div&gt;
        ///	&lt;hr /&gt;
        ///	&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Html_UpdateState {
            get {
                return ResourceManager.GetString("File_Html_UpdateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (function() {
        ///	var link = document.getElementsByTagName(&apos;a&apos;);
        ///
        ///	for (var i = 0; i &lt; link.length; i++) {
        ///		var a = link[i];
        ///		a.setAttribute(&apos;target&apos;, &apos;_blank&apos;);
        ///	}
        ///})()
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_JavaScript_GeckoFx_AcceptLink {
            get {
                return ResourceManager.GetString("File_JavaScript_GeckoFx_AcceptLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;UserControl 
        ///  x:Name=&quot;dummy&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///  xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///  d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;300&quot;
        ///&gt;
        ///  &lt;Button Style=&quot;{StaticResource Hyperlink}&quot; Command=&quot;{Binding ${command}}&quot; CommandParameter=&quot;${link}&quot;&gt;
        ///    &lt;TextBlock Text=&apos;${text}&apos; /&gt;
        ///  &lt;/Button&gt;
        ///&lt;/UserControl&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Xaml_DescriptionLink {
            get {
                return ResourceManager.GetString("File_Xaml_DescriptionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;UserControl 
        ///  x:Name=&quot;dummy&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///  
        ///  xmlns:app_view_converter=&quot;clr-namespace:ContentTypeTextNet.MnMn.MnMn.View.Converter;assembly=ContentTypeTextNet.MnMn.MnMn&quot;
        ///  
        ///  xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///  d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;300&quot;
        ///&gt;
        ///  &lt;MenuItem Header=&quot;${header}&quot; Font [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Xaml_DescriptionMenuItem {
            get {
                return ResourceManager.GetString("File_Xaml_DescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;UserControl 
        ///  x:Name=&quot;dummy&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///  
        ///  xmlns:app_view_converter=&quot;clr-namespace:ContentTypeTextNet.MnMn.MnMn.View.Converter;assembly=ContentTypeTextNet.MnMn.MnMn&quot;
        ///  
        ///  xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///  d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;300&quot;
        ///&gt;
        ///  &lt;Separator /&gt;
        ///&lt;/UserControl&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Xaml_DescriptionMenuSeparator {
            get {
                return ResourceManager.GetString("File_Xaml_DescriptionMenuSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;UserControl 
        ///  x:Name=&quot;dummy&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///  xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///  d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;300&quot;
        ///&gt;
        ///  &lt;Viewbox Style=&quot;{StaticResource SmallIconBox}&quot;&gt;
        ///    &lt;Canvas Style=&quot;{StaticResource IconCanvas-24x24}&quot;&gt;
        ///      &lt;Path Data=&quot;{StaticResource ${icon-key}}&quot; Style=&quot;{Static [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Xaml_SmallIcon {
            get {
                return ResourceManager.GetString("File_Xaml_SmallIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;UserControl
        ///  x:Name=&quot;dummy&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///&gt;
        ///  &lt;Image
        ///    Style=&quot;{StaticResource SmallIconImage}&quot;
        ///    Source=&quot;{Binding ${image}}&quot;
        ///  /&gt;
        ///&lt;/UserControl&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Xaml_SmallImage {
            get {
                return ResourceManager.GetString("File_Xaml_SmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_AllSelect {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_AllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_Back {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択をコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_CopySelection {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_CopySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_Forward {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_Property {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⛄ソース⛇ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_ShowSource {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_ShowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Common_Source {
            get {
                return ResourceManager.GetString("String_App_Browser_Common_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Download_AllFile_Display {
            get {
                return ResourceManager.GetString("String_App_Browser_Download_AllFile_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Browser_Download_AllFile_Pattern {
            get {
                return ResourceManager.GetString("String_App_Browser_Download_AllFile_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダム再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_CheckedProcessType_RandomPlay {
            get {
                return ResourceManager.GetString("String_App_Define_CheckedProcessType_RandomPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連続再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_CheckedProcessType_SequencePlay {
            get {
                return ResourceManager.GetString("String_App_Define_CheckedProcessType_SequencePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前方一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_ForwardMatch {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_ForwardMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_PartialMatch {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_PartialMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_PerfectMatch {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_PerfectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_Regex {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Laboratory_Service_Smile_Video_CommentCreateType_Random {
            get {
                return ResourceManager.GetString("String_App_Define_Laboratory_Service_Smile_Video_CommentCreateType_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インクリメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Laboratory_Service_Smile_Video_CommentCreateType_Sequence {
            get {
                return ResourceManager.GetString("String_App_Define_Laboratory_Service_Smile_Video_CommentCreateType_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インクリメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Laboratory_VideoCreateType_Sequence {
            get {
                return ResourceManager.GetString("String_App_Define_Laboratory_VideoCreateType_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Loaded {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Loading {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_None {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Preparation {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_Check {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_In {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_LoggedIn {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_None {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SearchType_Keyword {
            get {
                return ResourceManager.GetString("String_App_Define_SearchType_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SearchType_Tag {
            get {
                return ResourceManager.GetString("String_App_Define_SearchType_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PostKey取得がダメダメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_Comment_PostKeyError {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_Comment_PostKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Command {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Comment {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_UserId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿拒否 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポストキーがおかしい or ユーザーIDがおかしい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidPostkey {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidPostke" +
                        "y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スレッドIDがおかしい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidThread {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidThread" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿チケットが違う に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidTicket {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidTicket" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントはブロックされている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Locked {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントは書き込めない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Readonly {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Success {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント内容が長すぎる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_TooLong {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Unknown {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネルID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelName {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelName" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Description {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Description" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Tag {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Title {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserName {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_VideoId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_VideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_CommentCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_FirstRetrieve {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_FirstRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Length {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_MyListCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_MyListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Number {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Title {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_ViewCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoUserKind_Alert {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoUserKind_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoUserKind_Noraml {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoUserKind_Noraml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運営 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoUserKind_Official {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoUserKind_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレミアム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoUserKind_Premium {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoUserKind_Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生放送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoUserKind_Real {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoUserKind_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ニコニコ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_ServiceType_Smile {
            get {
                return ResourceManager.GetString("String_App_Define_ServiceType_Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ニコニコ生放送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_ServiceType_SmileLive {
            get {
                return ResourceManager.GetString("String_App_Define_ServiceType_SmileLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ニコニコ動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_ServiceType_SmileVideo {
            get {
                return ResourceManager.GetString("String_App_Define_ServiceType_SmileVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_Completed {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報取得中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_InformationLoading {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_InformationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_None {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソースチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_SourceChecking {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_SourceChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソース読込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_SourceLoading {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_SourceLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UI_Player_BackgroundKind_AutoColor {
            get {
                return ResourceManager.GetString("String_App_Define_UI_Player_BackgroundKind_AutoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UI_Player_BackgroundKind_SimpleColor {
            get {
                return ResourceManager.GetString("String_App_Define_UI_Player_BackgroundKind_SimpleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何もしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UI_Player_WheelOperation_None {
            get {
                return ResourceManager.GetString("String_App_Define_UI_Player_WheelOperation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーク調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UI_Player_WheelOperation_Seek {
            get {
                return ResourceManager.GetString("String_App_Define_UI_Player_WheelOperation_Seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UI_Player_WheelOperation_Volume {
            get {
                return ResourceManager.GetString("String_App_Define_UI_Player_WheelOperation_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在バージョンは最新版です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_CurrentIsNew {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_CurrentIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新バージョン🐜 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_CurrentIsOld {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_CurrentIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_Error {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_UnChecked {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   簡易アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_EazyUpdate {
            get {
                return ResourceManager.GetString("String_App_EazyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この MnMn はβ版ですが、β版として起動されていません。
        ///明示的な起動(/execute-beta)が行われておらず、設定データ・キャッシュがリリース版と混在する可能性があるためこのまま続行することはお勧めしません。
        ///β版をリリース版と混合せず使用するには &quot;&lt;MnMn&gt;\bat\beta.bat&quot; を実行してください。
        ///
        ///このまま起動してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_ExecuteBetaVersion_Warning {
            get {
                return ResourceManager.GetString("String_App_ExecuteBetaVersion_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URIをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_IDescription_MenuCopyUri {
            get {
                return ResourceManager.GetString("String_App_IDescription_MenuCopyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準ブラウザで開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_IDescription_MenuOpenUri {
            get {
                return ResourceManager.GetString("String_App_IDescription_MenuOpenUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内蔵ブラウザで開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_IDescription_MenuOpenUriInAppBrowser {
            get {
                return ResourceManager.GetString("String_App_IDescription_MenuOpenUriInAppBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保護されたヘッダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Logic_PageLoader_SafetyHeader {
            get {
                return ResourceManager.GetString("String_App_Logic_PageLoader_SafetyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保護されたパラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Logic_PageLoader_SafetyParameter {
            get {
                return ResourceManager.GetString("String_App_Logic_PageLoader_SafetyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保護されたURI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Logic_PageLoader_SafetyUri {
            get {
                return ResourceManager.GetString("String_App_Logic_PageLoader_SafetyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   報告用設定・情報データファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Setting_PublicExportFileName {
            get {
                return ResourceManager.GetString("String_App_Setting_PublicExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未定義ジェスチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Unknown_Gesture {
            get {
                return ResourceManager.GetString("String_App_Unknown_Gesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新バージョン(${NEW-VERSION})がリリースされています。
        ///現バージョン(${NOW-VERSION})から更新を行いますか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Update_Format {
            get {
                return ResourceManager.GetString("String_App_Update_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートチェック状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Update_Title {
            get {
                return ResourceManager.GetString("String_App_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Log_Filter_Log {
            get {
                return ResourceManager.GetString("String_Log_Filter_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あとで見るに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuAddCheckItLaterVideoId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuAddCheckItLaterVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブックマーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuAddMyListId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuAddMyListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイリストに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuAddPlayListVideoId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuAddPlayListVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未整理のブックマークに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuAddUnorganizedBookmarkVideoId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuAddUnorganizedBookmarkVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリストIDをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuCopyMyListId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuCopyMyListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画IDのコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuCopyVideoId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuCopyVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuOpenMyListId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuOpenMyListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のプレイヤーで再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuOpenVideoId {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuOpenVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規プレイヤーで再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_ISmileDescription_MenuOpenVideoIdInNewWindow {
            get {
                return ResourceManager.GetString("String_Service_Smile_ISmileDescription_MenuOpenVideoIdInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいマイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_MyList_CreateGroupName {
            get {
                return ResourceManager.GetString("String_Service_Smile_MyList_CreateGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とりあえずマイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_MyList_DefaultMyListName {
            get {
                return ResourceManager.GetString("String_Service_Smile_MyList_DefaultMyListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVide_Launcher_Item_Any {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVide_Launcher_Item_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVide_Launcher_Item_Program {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVide_Launcher_Item_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規ブックマーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Bookmark_NewName {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Bookmark_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未整理のブックマーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Bookmark_Unorganized {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Bookmark_Unorganized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重複コメントフィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Comment_NoApproval_Detail_Overlap {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Comment_NoApproval_Detail_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全ての動画のフィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Comment_NoApproval_GlobalFilter {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Comment_NoApproval_GlobalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この動画のフィルタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Comment_NoApproval_LocalFilter {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Comment_NoApproval_LocalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共有NG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Comment_NoApproval_SharedNoGood {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Comment_NoApproval_SharedNoGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_History_AccountHistory_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_History_AccountHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_History_ApplicationHistory_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_History_ApplicationHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Hotlist_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Hotlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着投稿動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_NewArrival_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_NewArrival_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着コメント動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Recent_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Recent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたにおすすめ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Recommendations_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Recommendations_Title", resourceCulture);
            }
        }
    }
}
