//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.MnMn.MnMn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.MnMn.MnMn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   前方一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_ForwardMatch {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_ForwardMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_PartialMatch {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_PartialMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_PerfectMatch {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_PerfectMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_FilteringType_Regex {
            get {
                return ResourceManager.GetString("String_App_Define_FilteringType_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Loaded {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Loading {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_None {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoadState_Preparation {
            get {
                return ResourceManager.GetString("String_App_Define_LoadState_Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_Check {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_In {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_LoggedIn {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_LoginState_None {
            get {
                return ResourceManager.GetString("String_App_Define_LoginState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PostKey取得がダメダメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_Comment_PostKeyError {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_Comment_PostKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Command {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Comment {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_UserId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentFilteringTarget_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿拒否 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポストキーがおかしい or ユーザーIDがおかしい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidPostkey {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidPostke" +
                        "y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スレッドIDがおかしい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidThread {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidThread" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿チケットが違う に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidTicket {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_InvalidTicket" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントはブロックされている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Locked {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントは書き込めない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Readonly {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Success {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント内容が長すぎる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_TooLong {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Unknown {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoCommentResultStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネルID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelName {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_ChannelName" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Description {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Description" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Tag {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Title {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserName {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_VideoId {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoFinderFilteringTarget_VideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_CommentCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_FirstRetrieve {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_FirstRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Length {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_MyListCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_MyListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Number {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Title {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_ViewCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ニコニコ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_ServiceType_Smile {
            get {
                return ResourceManager.GetString("String_App_Define_ServiceType_Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ニコニコ動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_ServiceType_SmileVideo {
            get {
                return ResourceManager.GetString("String_App_Define_ServiceType_SmileVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_Completed {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_Failure {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報取得中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_InformationLoading {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_InformationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_None {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソースチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_SourceChecking {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_SourceChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソース読込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_SourceLoadState_SourceLoading {
            get {
                return ResourceManager.GetString("String_App_Define_SourceLoadState_SourceLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在バージョンは最新版です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_CurrentIsNew {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_CurrentIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新バージョン🐜 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_CurrentIsOld {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_CurrentIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_Error {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_UpdateCheckState_UnChecked {
            get {
                return ResourceManager.GetString("String_App_Define_UpdateCheckState_UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新バージョン(${NEW-VERSION})がリリースされています。
        ///現バージョン(${NOW-VERSION})から更新を行いますか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Update_Format {
            get {
                return ResourceManager.GetString("String_App_Update_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートチェック状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Update_Title {
            get {
                return ResourceManager.GetString("String_App_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Log_Filter_Log {
            get {
                return ResourceManager.GetString("String_Log_Filter_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいマイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_MyList_CreateGroupName {
            get {
                return ResourceManager.GetString("String_Service_Smile_MyList_CreateGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とりあえずマイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_MyList_DefaultMyListName {
            get {
                return ResourceManager.GetString("String_Service_Smile_MyList_DefaultMyListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規ブックマーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Bookmark_NewName {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Bookmark_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_History_AccountHistory_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_History_AccountHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_History_ApplicationHistory_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_History_ApplicationHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Hotlist_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Hotlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着投稿動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_NewArrival_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_NewArrival_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着コメント動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Recent_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Recent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたにおすすめ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Recommendations_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Recommendations_Title", resourceCulture);
            }
        }
    }
}
