//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.MnMn.MnMn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.MnMn.MnMn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   コメント数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_CommentCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_FirstRetrieve {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_FirstRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Length {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_MyListCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_MyListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Number {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_Title {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Define_Service_Smile_Video_SmileVideoSortType_ViewCount {
            get {
                return ResourceManager.GetString("String_App_Define_Service_Smile_Video_SmileVideoSortType_ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規ブックマーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_Bookmark_NewName {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_Bookmark_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_History_AccountHistory_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_History_AccountHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_History_ApplicationHistory_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_History_ApplicationHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホットリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Hotlist_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Hotlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着投稿動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_NewArrival_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_NewArrival_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新着コメント動画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Recent_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Recent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたにおすすめ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Service_Smile_SmileVideo_NewArrivals_Recommendations_Title {
            get {
                return ResourceManager.GetString("String_Service_Smile_SmileVideo_NewArrivals_Recommendations_Title", resourceCulture);
            }
        }
    }
}
