//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.MnMn.Setup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.MnMn.Setup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_End {
            get {
                return ResourceManager.GetString("String_App_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_App_Start {
            get {
                return ResourceManager.GetString("String_App_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新アーカイブ取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_DownloadArchive {
            get {
                return ResourceManager.GetString("String_DownloadArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブデータ長未取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_DownloadArchive_Disabled_ContentLength {
            get {
                return ResourceManager.GetString("String_DownloadArchive_Disabled_ContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブデータ({0} byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_DownloadArchive_Enabled_ContentLength_Format {
            get {
                return ResourceManager.GetString("String_DownloadArchive_Enabled_ContentLength_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブデータ取得終了(所要時間: ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_DownloadArchive_End_Format {
            get {
                return ResourceManager.GetString("String_DownloadArchive_End_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブデータ取得開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_DownloadArchive_Start {
            get {
                return ResourceManager.GetString("String_DownloadArchive_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブ展開・ファイル配置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Expand {
            get {
                return ResourceManager.GetString("String_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新情報取得開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_GetArchiveInformation {
            get {
                return ResourceManager.GetString("String_GetArchiveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新情報: バージョン {0}, Uri = {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_GetArchiveInformation_Fromat {
            get {
                return ResourceManager.GetString("String_GetArchiveInformation_Fromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTTP通信: {0}, ステータスコード: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Http_Response_Header_Format {
            get {
                return ResourceManager.GetString("String_Http_Response_Header_Format", resourceCulture);
            }
        }
    }
}
